//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACUERDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACUERDO()
        {
            this.FORMATO_ACUERDO = new HashSet<FORMATO_ACUERDO>();
        }
    
        public int IdAcuerdo { get; set; }
        public int IdTipoAcuerdo { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaAcuerdo { get; set; }
        public int IdEntidadContraparte { get; set; }
        public string Duracion { get; set; }
        public int IdEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMATO_ACUERDO> FORMATO_ACUERDO { get; set; }
    }
}
