//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACUERDO_ARCHIVO
    {
        public int IdAcuerdoArchivo { get; set; }
        public int IdAcuerdo { get; set; }
        public int IdUrlLink { get; set; }
        public string NombreArchivo { get; set; }
        public int IdTipoArchivo { get; set; }
    
        public virtual ACUERDO ACUERDO { get; set; }
    }
}
