//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPO_REGLA
    {
        public int IdFormatoCampo { get; set; }
        public int IdRegla { get; set; }
        public int IdPlantillaCampo { get; set; }
        public int IdEstado { get; set; }
    
        public virtual PLANTILLA_CAMPO PLANTILLA_CAMPO { get; set; }
        public virtual REGLA REGLA { get; set; }
    }
}
