//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANAL_VALOR
    {
        public int IdCanalValor { get; set; }
        public int IdCampo { get; set; }
        public int IdCanalRegistro { get; set; }
        public string ValorAlfanumerico { get; set; }
        public Nullable<int> ValorEntero { get; set; }
        public Nullable<decimal> ValorDinero { get; set; }
        public Nullable<decimal> ValorTasa { get; set; }
        public Nullable<System.DateTime> ValorFecha { get; set; }
    
        public virtual CANAL_CAMPO CANAL_CAMPO { get; set; }
        public virtual CANAL_REGISTRO CANAL_REGISTRO { get; set; }
    }
}
