//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANAL_CAMPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANAL_CAMPO()
        {
            this.CANAL_VALOR = new HashSet<CANAL_VALOR>();
        }
    
        public int IdCampo { get; set; }
        public int IdCanal { get; set; }
        public string Campo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdTipoDato { get; set; }
        public Nullable<int> Tamaño { get; set; }
        public Nullable<bool> Editable { get; set; }
    
        public virtual CANAL CANAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANAL_VALOR> CANAL_VALOR { get; set; }
    }
}
