//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDAD_SERVICIO
    {
        public int IdEntidadServicio { get; set; }
        public int IdEntidad { get; set; }
        public int IdServicioSubTipo { get; set; }
        public int IdEstado { get; set; }
    
        public virtual ENTIDAD ENTIDAD { get; set; }
        public virtual SERVICIO_SUBTIPO SERVICIO_SUBTIPO { get; set; }
    }
}
