//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMATO
    {
        public FORMATO()
        {
            this.FORMATO_PLANTILLA = new HashSet<FORMATO_PLANTILLA>();
        }
    
        public int IdFormato { get; set; }
        public Nullable<int> IdNorma { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public int IdTipoFormato { get; set; }
        public int IdPlazo { get; set; }
        public int IdPeriodicidad { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> DiasPlazo { get; set; }
        public Nullable<int> IdSeccion { get; set; }
        public Nullable<bool> InlcuyeFecha { get; set; }
    
        public virtual NORMA NORMA { get; set; }
        public virtual PERIODICIDAD PERIODICIDAD { get; set; }
        public virtual ICollection<FORMATO_PLANTILLA> FORMATO_PLANTILLA { get; set; }
        public virtual PLAZO PLAZO { get; set; }
    }
}
