//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMATO_PLANTILLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORMATO_PLANTILLA()
        {
            this.FORMATO_ACUERDO = new HashSet<FORMATO_ACUERDO>();
            this.FORMATO_SERVICIO = new HashSet<FORMATO_SERVICIO>();
            this.PLANTILLA_CAMPO = new HashSet<PLANTILLA_CAMPO>();
        }
    
        public int IdFormatoPlantilla { get; set; }
        public int IdFormato { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual FORMATO FORMATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMATO_ACUERDO> FORMATO_ACUERDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMATO_SERVICIO> FORMATO_SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANTILLA_CAMPO> PLANTILLA_CAMPO { get; set; }
    }
}
