//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTEROPERATIVIDAD
    {
        public int IdInterOperatividad { get; set; }
        public string Ip { get; set; }
        public int Puerto { get; set; }
        public string URLLink { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
    }
}
