//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebApiDbEntities : DbContext
    {
        public WebApiDbEntities()
            : base("name=WebApiDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CANAL> CANAL { get; set; }
        public DbSet<CANAL_CAMPO> CANAL_CAMPO { get; set; }
        public DbSet<CANAL_REGISTRO> CANAL_REGISTRO { get; set; }
        public DbSet<CANAL_VALOR> CANAL_VALOR { get; set; }
        public DbSet<ENTIDAD_CANAL> ENTIDAD_CANAL { get; set; }
        public DbSet<ACUERDO> ACUERDO { get; set; }
        public DbSet<FORMATO> FORMATO { get; set; }
        public DbSet<FORMATO_ACUERDO> FORMATO_ACUERDO { get; set; }
        public DbSet<FORMATO_PLANTILLA> FORMATO_PLANTILLA { get; set; }
        public DbSet<FORMATO_SERVICIO> FORMATO_SERVICIO { get; set; }
        public DbSet<NORMA> NORMA { get; set; }
        public DbSet<NORMA_SECTOR> NORMA_SECTOR { get; set; }
        public DbSet<PLANTILLA_CAMPO> PLANTILLA_CAMPO { get; set; }
        public DbSet<CAMPO_REGLA> CAMPO_REGLA { get; set; }
        public DbSet<ENTIDAD> ENTIDAD { get; set; }
        public DbSet<ENTIDAD_SERVICIO> ENTIDAD_SERVICIO { get; set; }
        public DbSet<REGLA> REGLA { get; set; }
        public DbSet<SECTOR_SERVICIO> SECTOR_SERVICIO { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<SERVICIO_SUBTIPO> SERVICIO_SUBTIPO { get; set; }
        public DbSet<TABLA> TABLA { get; set; }
        public DbSet<TABLA_CAMPO> TABLA_CAMPO { get; set; }
        public DbSet<TABLA_REGISTRO> TABLA_REGISTRO { get; set; }
        public DbSet<TABLA_VALOR> TABLA_VALOR { get; set; }
    }
}
