//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIODO
    {
        public int IdPeriodo { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public int IdPeriodicidad { get; set; }
        public int MesInicio { get; set; }
        public int MesFin { get; set; }
    
        public virtual PERIODICIDAD PERIODICIDAD { get; set; }
    }
}
