//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTILLA_CAMPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANTILLA_CAMPO()
        {
            this.CAMPO_REGLA = new HashSet<CAMPO_REGLA>();
        }
    
        public int IdPlantillaCampo { get; set; }
        public int IdFormatoPlantilla { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public int IdTipoDato { get; set; }
        public int Tamaño { get; set; }
        public int IdEstado { get; set; }
    
        public virtual FORMATO_PLANTILLA FORMATO_PLANTILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPO_REGLA> CAMPO_REGLA { get; set; }
    }
}
