//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAZO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLAZO()
        {
            this.FORMATO = new HashSet<FORMATO>();
        }
    
        public int IdPlazo { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public bool CalcularFecha { get; set; }
        public bool PeriodoVencido { get; set; }
        public bool UltimoDia { get; set; }
        public int TipoDia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<FORMATO> FORMATO { get; set; }
    }
}
