//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTOR_SERVICIO
    {
        public SECTOR_SERVICIO()
        {
            this.NORMA_SECTOR = new HashSet<NORMA_SECTOR>();
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public int IdSectorServicio { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int IdEstado { get; set; }
    
        public virtual ICollection<NORMA_SECTOR> NORMA_SECTOR { get; set; }
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
