//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLA_REGISTRO
    {
        public TABLA_REGISTRO()
        {
            this.TABLA_VALOR = new HashSet<TABLA_VALOR>();
        }
    
        public int IdTablaRegistro { get; set; }
        public int IdTabla { get; set; }
    
        public virtual TABLA TABLA { get; set; }
        public virtual ICollection<TABLA_VALOR> TABLA_VALOR { get; set; }
    }
}
