//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLA
    {
        public TABLA()
        {
            this.TABLA_CAMPO = new HashSet<TABLA_CAMPO>();
            this.TABLA_REGISTRO = new HashSet<TABLA_REGISTRO>();
        }
    
        public int IdTabla { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int IdEstado { get; set; }
        public int IdTipoTabla { get; set; }
    
        public virtual ICollection<TABLA_CAMPO> TABLA_CAMPO { get; set; }
        public virtual ICollection<TABLA_REGISTRO> TABLA_REGISTRO { get; set; }
    }
}
