//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebApiDbEntities : DbContext
    {
        public WebApiDbEntities()
            : base("name=WebApiDbEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CANAL> CANAL { get; set; }
        public virtual DbSet<CANAL_CAMPO> CANAL_CAMPO { get; set; }
        public virtual DbSet<CANAL_REGISTRO> CANAL_REGISTRO { get; set; }
        public virtual DbSet<CANAL_VALOR> CANAL_VALOR { get; set; }
        public virtual DbSet<ENTIDAD_CANAL> ENTIDAD_CANAL { get; set; }
        public virtual DbSet<ACUERDO> ACUERDO { get; set; }
        public virtual DbSet<FORMATO> FORMATO { get; set; }
        public virtual DbSet<FORMATO_ACUERDO> FORMATO_ACUERDO { get; set; }
        public virtual DbSet<FORMATO_PLANTILLA> FORMATO_PLANTILLA { get; set; }
        public virtual DbSet<FORMATO_SERVICIO> FORMATO_SERVICIO { get; set; }
        public virtual DbSet<NORMA> NORMA { get; set; }
        public virtual DbSet<NORMA_SECTOR> NORMA_SECTOR { get; set; }
        public virtual DbSet<PLANTILLA_CAMPO> PLANTILLA_CAMPO { get; set; }
        public virtual DbSet<CAMPO_REGLA> CAMPO_REGLA { get; set; }
        public virtual DbSet<DIAFESTIVO> DIAFESTIVO { get; set; }
        public virtual DbSet<ENTIDAD> ENTIDAD { get; set; }
        public virtual DbSet<ENTIDAD_SERVICIO> ENTIDAD_SERVICIO { get; set; }
        public virtual DbSet<PERIODICIDAD> PERIODICIDAD { get; set; }
        public virtual DbSet<PERIODO> PERIODO { get; set; }
        public virtual DbSet<PLAZO> PLAZO { get; set; }
        public virtual DbSet<REGLA> REGLA { get; set; }
        public virtual DbSet<SECTOR_SERVICIO> SECTOR_SERVICIO { get; set; }
        public virtual DbSet<SERVICIO> SERVICIO { get; set; }
        public virtual DbSet<TABLA> TABLA { get; set; }
        public virtual DbSet<TABLA_CAMPO> TABLA_CAMPO { get; set; }
        public virtual DbSet<TABLA_REGISTRO> TABLA_REGISTRO { get; set; }
        public virtual DbSet<TABLA_VALOR> TABLA_VALOR { get; set; }
    }
}
